#pragma once

#include "bits/mdspan.hpp"
#include "bits/subspan.hpp"
#include "bits/extents.hpp"
#include "bits/decomposition.hpp"
#include "bits/loop.hpp"
#include "bits/neighbours.hpp"
#include "bits/for_each_index.hpp"
#include "bits/evaluate_tiled.hpp"
#include "bits/evaluate_boundary.hpp"
#include "bits/rank.hpp"
#include "bits/index_conversions.hpp"
#include "bits/algorithms.hpp"
#include "bits/divide_equally.hpp"
